version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres-compose-network

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "bile"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bile"
      PGADMIN_DEFAULT_PASSWORD: "bile"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge