version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "bile"
    ports:
      - "5432:5432"
    volumes:
      - /home/allan.barbosa/go/src/github.com/allbarbos/go/alura-web/postgresql/volume:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bile"
      PGADMIN_DEFAULT_PASSWORD: "bile"
    ports:
      - "8001:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

# REF: https://medium.com/@renato.groffe/postgresql-pgadmin-4-docker-compose-montando-rapidamente-um-ambiente-para-uso-55a2ab230b89